### PR TITLE
Cas 13520 add documentation for new task, imbaseline

### PR DESCRIPTION
**Pull request by tnakazato**

### CODE REVIEW

**Comment by tnakazato** [comment]
@bemonts, we've created casadocs task description for imbaseline. Could you review the content? Please feel free to merge if the description is fine.

**Review by bemonts — APPROVED** [review]
@SatokoTakahashi and @tnakazato , thanks a lot for writing the imbaseline documentation! Great timing, as I plan to take the CASA Docs snap-shot for the 6.5 release today, so this will be included. It looks complete to me, but because this is an .rst file, it is difficult to see if all will translate ok into CASA Docs (including the parameter from the XML). So I will make the merge, and then do a final check if all looks ok once it appears on master. Thanks again for the quick turn-around in writing this!!

**Comment by bemonts** [comment]
See my comments under the review. Thanks a lot @SatokoTakahashi and @tnakazato !

**Comment by bemonts** [comment]
@SatokoTakahashi and @tnakazato , after merging this to master, I noticed that it ends up under "analysis" tasks. Should the better place not be "Single Dish tasks", which I think includes all other single dish tasks? 
See:  https://casadocs.readthedocs.io/en/latest/api/casatasks.html
What do you think?

I have been trying to move this, but don't manage, and suspect that the path to casatasks.single instead of casatasks.analysis needs to be changed in the XML (to which I have no access), but I am not sure. I am trying to find out with the team here, but if you have any feedback (either on whether this is preferred, and/or how to do this), please let me know. Thanks a lot!

**Comment by tnakazato** [comment]
@bemonts, I think analysis category is fine. That is because imbaseline is so generic that it can process images produced by interferometry imaging like tclean (in short, imbaseline is a variant of imfit).

**Comment by bemonts** [comment]
@tnakazato: Ok, no problem, we will keep it under "analysis. Thanks again!!

**Pull request merged**
