### PR TITLE
documentation update for CAS-13160

### PR DESCRIPTION
**Pull request by tnakazato**

### CODE REVIEW

**Comment by tnakazato** [comment]
Automatic build worked. Result looks fine. 

https://casadocs--5.org.readthedocs.build/en/5/

**Comment by tnakazato** [comment]
@ryanraba, @bemonts, could you review this PR? This blocks the completion of CAS-13160 so it would be great if you could review this week. Thanks.

**Comment by bemonts** [comment]
Hi Takeshi, your first request for review escaped my attention (still trying to understand the workflow of the new github docs...) 
Thanks a lot for adding this nice page on sdatmcor to CASA Docs. It looks great to me and ready for merge - please pull the trigger when ready!
Cheers, Bjorn

**Comment by tnakazato** [comment]
Thanks @bemonts for the review. I will merge this to master.

**Pull request merged**
