### PR TITLE
CAS-13883: casadocs task and tool pages: parameter (multi)types are broken in releases >=6.4.0

### PR DESCRIPTION
**Pull request by FedeMPouzols**
PR for https://open-jira.nrao.edu/browse/CAS-13883

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
The build of this branch (I just merged master before opening the PR) failed, and the 'latest' build started failing yesterday: https://readthedocs.org/projects/casadocs/builds/
There seems to be some pandoc problem, but the error messages look vaguely familiar or similar to the erros we were getting when the casa6 repo was not public (around a couple of weeks ago).

**Comment by FedeMPouzols** [comment]
The issue in recent builds of casadocs comes from pypandoc (download_pandoc()) function), which has stopped working after github updated its release download pages.  Issue: https://github.com/JessicaTegner/pypandoc/issues/295, fix being worked on: https://github.com/JessicaTegner/pypandoc/pull/296

Once there is a release of pypandoc with this fix, casadocs should update its requirements.txt to use it.

**Comment by bemonts** [comment]
Thanks @FedeMPouzols  for figuring out the problem. Do you know where we can track the status for release of pypandoc with fix?

**Comment by smcastro** [comment]
Thanks Federico. The changes look good to me, although it would be better to wait for the build to be fixed to see the rendered pages.

**Comment by FedeMPouzols** [comment]
Yes, the pypandoc fix is for now in this PR to the pypandoc repo: https://github.com/JessicaTegner/pypandoc/pull/296

**Comment by FedeMPouzols** [comment]
Merging this branch for 6.5.2.

As discussed in the chat, after this temporari fix: https://github.com/casangi/casadocs/commit/3f98ee780968225d7fefc0e89872c2918829c28b, the casadocs builds are working again. After merging master with that update into this branch the docs were rendered again and they looked fine.

**Comment by bemonts** [comment]
Thanks, @FedeMPouzols !!

**Pull request merged**
